server:
  port: 9005

spring:
  datasource:
    username: bj
    password: bj2016
    url: jdbc:mysql://192.168.10.231:3307/shekong_data?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    username: fenxi
#    password: fenxi%2021
#    url: jdbc:mysql://10.126.105.5:3306/gd_data?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:log4j2.xml