server:
  port: 9800

spring:
  datasource:
    username: root
    password: 981710Tzc
    url: jdbc:mysql://localhost:3306/tools?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
