server:
  port: 8080

spring:
  datasource:
    username: bj
    password: bj2016
    url: jdbc:mysql://192.168.10.231:3307/gd_data?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
